animations=0
layer_animations=0
animation_fade_in=0
animation_fade_out=0
blur=0
blur_layer=0
shadows=0
layer_shadows=0
border_radius=0
focused_opacity=1.0
unfocused_opacity=1.0

borderpx=1
gappih=0
gappiv=0
gappoh=0
gappov=0
smartgaps=0
group_bar_height=0

rootcolor=0x000000ff
bordercolor=0x2a2a2aff
focuscolor=0x4a4a4aff
urgentcolor=0xa04040ff
maximizescreencolor=0x4a4a4aff
scratchpadcolor=0x4a4a4aff
globalcolor=0x4a4a4aff
overlaycolor=0x4a4a4aff
splitcolor=0x4a4a4aff
dropcolor=0x4a4a4aff
jump_label_decorate_font_desc=JetBrainsMono Nerd Font 10

enable_hotarea=0
sloppyfocus=0
warpcursor=0
tag_num=9

exec-once=~/.config/ibr/autostart

bind=SUPER,Return,spawn,@TERM@
bind=SUPER,d,spawn,@MENU@
bind=SUPER+SHIFT,q,killclient
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,space,togglefloating
bind=SUPER+SHIFT,c,reload_config
bind=SUPER+SHIFT,e,quit

bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
bind=SUPER,l,focusdir,right
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+SHIFT,1,tagsilent,1
bind=SUPER+SHIFT,2,tagsilent,2
bind=SUPER+SHIFT,3,tagsilent,3
bind=SUPER+SHIFT,4,tagsilent,4
bind=SUPER+SHIFT,5,tagsilent,5
bind=SUPER+SHIFT,6,tagsilent,6
bind=SUPER+SHIFT,7,tagsilent,7
bind=SUPER+SHIFT,8,tagsilent,8
bind=SUPER+SHIFT,9,tagsilent,9

bind=NONE,Print,spawn_shell,@SHOT@

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
