#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 0
bspc config normal_border_color "#2a2a2a"
bspc config active_border_color "#2a2a2a"
bspc config focused_border_color "#4a4a4a"
bspc config presel_feedback_color "#4a4a4a"

xsetroot -solid "#000000"

# no keybinds without this
pgrep -x sxhkd >/dev/null || sxhkd &

~/.config/ibr/autostart
