color=000000
ignore-empty-password

daemonize

indicator-radius=24
indicator-thickness=1

inside-color=000000
inside-clear-color=000000
inside-ver-color=000000
inside-wrong-color=000000

ring-color=2a2a2a
ring-clear-color=2a2a2a
ring-ver-color=4a4a4a
ring-wrong-color=a04040

key-hl-color=4a4a4a
bs-hl-color=a04040

text-color=000000
