$mod = SUPER

monitor = , preferred, auto, 1

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgb(4a4a4a)
    col.inactive_border = rgb(2a2a2a)
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    dim_inactive = false

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = rgb(000000)
}

input {
    follow_mouse = 0
}

cursor {
    inactive_timeout = 8
}

bind = $mod, Return, exec, @TERM@
bind = $mod, D, exec, @MENU@
bind = $mod SHIFT, Q, killactive
bind = $mod, F, fullscreen, 0
bind = $mod SHIFT, Space, togglefloating
bind = $mod SHIFT, C, exec, hyprctl reload
bind = $mod SHIFT, E, exit

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

bind = , Print, exec, @SHOT@

exec-once = ~/.config/ibr/autostart
